<a href="https://colab.research.google.com/github/swathi38538/BrickView-Project/blob/main/BrickView.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BrickView Real Estate Data Analysis

## STEP 1: Import Required Libraries

In [ ]:
import pandas as pd
import sqlite3
import json

## STEP 2: Load Dataset Files

In [ ]:
import pandas as pd

# Load all datasets
listings = pd.read_json("data/listings_final_expanded.json")
properties = pd.read_json("data/property_attributes_final_expanded.json")
agents = pd.read_json("data/agents_cleaned.json")
buyers = pd.read_json("data/buyers_cleaned.json")
sales = pd.read_csv("data/sales_cleaned.csv")

print("✅ All datasets loaded successfully!\n")

print("Listings Shape:", listings.shape)
print("Properties Shape:", properties.shape)
print("Agents Shape:", agents.shape)
print("Buyers Shape:", buyers.shape)
print("Sales Shape:", sales.shape)

✅ All datasets loaded successfully!

Listings Shape: (21200, 9)
Properties Shape: (21200, 13)
Agents Shape: (50, 9)
Buyers Shape: (20000, 7)
Sales Shape: (720, 4)

## STEP 3: Connect to SQLite Database

In [ ]:
import sqlite3

# Connect to SQLite Database
conn = sqlite3.connect("brickview.db")

print("✅ Connected to BrickView Database Successfully!")

✅ Connected to BrickView Database Successfully!

## STEP 4: Verify Tables in Database

In [ ]:
cursor = conn.cursor()

cursor.execute("""
SELECT name
FROM sqlite_master
WHERE type='table';
""")

tables = cursor.fetchall()

print("Tables in the database:")

for table in tables:
    print(table[0])

Tables in the database:
Listings
Properties
Agents
Buyers
Sales

## Query 1: Average Listing Price by City

**Question:** What is the average listing price in each city?

In [ ]:
query1 = """
SELECT
    City,
    ROUND(AVG(Price),2) AS Average_Price
FROM Listings
GROUP BY City
ORDER BY Average_Price DESC;
"""

pd.read_sql_query(query1, conn)

          City  Average_Price
0     New York     2493319.74
1      Phoenix     2459961.76
2  Los Angeles     2442418.31
3      Houston     2436811.00
4      Chicago     2430677.90

## Query 2: Average Price per Square Foot by Property Type

**Question:** What is the average price per square foot for each property type?

In [ ]:
query2 = """
SELECT
    Property_Type,
    ROUND(AVG(Price / Sqft),2) AS Avg_Price_Per_Sqft
FROM Listings
GROUP BY Property_Type
ORDER BY Avg_Price_Per_Sqft DESC;
"""

pd.read_sql_query(query2, conn)

  Property_Type  Avg_Price_Per_Sqft
0         House              796.04
1     Apartment              792.20
2     Townhouse              789.75
3         Condo              754.68

## Query 3: Average Property Price by Furnishing Status

**Question:** How does furnishing status affect property prices?

In [ ]:
query3 = """
SELECT
    p.furnishing_status,
    ROUND(AVG(l.Price),2) AS Average_Price
FROM Listings l
INNER JOIN Properties p
ON l.Listing_ID = p.listing_id
GROUP BY p.furnishing_status
ORDER BY Average_Price DESC;
"""

pd.read_sql_query(query3, conn)

  furnishing_status  Average_Price
0         Furnished     2463539.06
1    Semi-Furnished     2461192.65
2       Unfurnished     2433975.10

## Query 4: Properties Near Metro Stations

**Question:** Do properties closer to metro stations command higher prices?

In [ ]:
query4 = """
SELECT
    CASE
        WHEN metro_distance_km <= 2 THEN 'Near Metro'
        ELSE 'Far from Metro'
    END AS Metro_Category,

    ROUND(AVG(l.Price), 2) AS Average_Price

FROM Listings l
INNER JOIN Properties p
ON l.Listing_ID = p.listing_id

GROUP BY Metro_Category;
"""

pd.read_sql_query(query4, conn)

   Metro_Category  Average_Price
0  Far from Metro     2464613.02
1      Near Metro     2377825.06

## Query 5: Rented vs Non-Rented Property Prices

**Question:** Are rented properties priced differently from non-rented ones?

In [ ]:
query5 = """
SELECT
    CASE
        WHEN p.is_rented = 1 THEN 'Rented'
        ELSE 'Not Rented'
    END AS Rental_Status,
    ROUND(AVG(l.Price), 2) AS Average_Price
FROM Listings l
INNER JOIN Properties p
ON l.Listing_ID = p.listing_id
GROUP BY p.is_rented;
"""

pd.read_sql_query(query5, conn)

  Rental_Status  Average_Price
0    Not Rented      2448250.3
1        Rented      2457184.9

## Query 6: Bedrooms and Bathrooms vs Property Pricing

**Question:** How do bedrooms and bathrooms affect pricing?

In [ ]:
query6 = """
SELECT
    p.bedrooms,
    p.bathrooms,
    ROUND(AVG(l.Price), 2) AS Average_Price
FROM Listings l
INNER JOIN Properties p
ON l.Listing_ID = p.listing_id
GROUP BY p.bedrooms, p.bathrooms
ORDER BY Average_Price DESC;
"""

pd.read_sql_query(query6, conn)

    bedrooms  bathrooms  Average_Price
0          2          4     2555766.23
1          5          4     2527191.97
2          1          2     2509474.77
3          2          3     2482618.93
4          3          4     2478881.22
5          5          2     2478068.17
6          4          4     2471535.90
7          1          3     2459032.59
8          2          1     2455735.36
9          1          4     2455532.96
10         3          3     2455024.25
11         4          2     2450749.99
12         4          1     2434956.38
13         1          1     2434001.41
14         3          1     2426007.97
15         5          3     2424066.83
16         3          2     2409122.73
17         4          3     2393515.03
18         5          1     2384940.47
19         2          2     2378687.66

## Query 7: Impact of Parking and Power Backup on Property Prices

**Question:** Do properties with parking and power backup sell at higher prices?

In [ ]:
query7 = """
SELECT
    parking_available,
    power_backup,
    ROUND(AVG(l.Price), 2) AS Average_Price
FROM Listings l
INNER JOIN Properties p
ON l.Listing_ID = p.listing_id
GROUP BY
    parking_available,
    power_backup
ORDER BY Average_Price DESC;
"""

pd.read_sql_query(query7, conn)

   parking_available  power_backup  Average_Price
0                  1             1     2465651.62
1                  1             0     2462363.80
2                  0             1     2446292.59
3                  0             0     2436677.75

## Query 8: Year Built vs Listing Price

**Question:** How does year built influence listing price?

In [ ]:
query8 = """
SELECT
    year_built,
    ROUND(AVG(l.Price), 2) AS Average_Price
FROM Listings l
INNER JOIN Properties p
ON l.Listing_ID = p.listing_id
GROUP BY year_built
ORDER BY year_built DESC;
"""

pd.read_sql_query(query8, conn)

    year_built  Average_Price
0         2023     2500120.42
1         2022     2397386.65
2         2021     2545272.16
3         2020     2465414.49
4         2019     2561310.32
5         2018     2385864.55
6         2017     2393633.46
7         2016     2428168.81
8         2015     2457272.07
9         2014     2358476.99
10        2013     2348081.45
11        2012     2302495.50
12        2011     2440249.43
13        2010     2401119.97
14        2009     2401619.13
15        2008     2471225.25
16        2007     2379428.80
17        2006     2464741.47
18        2005     2518303.24
19        2004     2410642.66
20        2003     2395754.95
21        2002     2433615.48
22        2001     2438764.29
23        2000     2436148.36
24        1999     2498402.48
25        1998     2398158.87
26        1997     2493105.20
27        1996     2391385.75
28        1995     2434727.72
29        1994     2571504.92
30        1993     2611748.25
31        1992     2594651.56
32        1991     2573916.58
33        1990     2533791.60

## Query 9: Cities with Highest Average Property Prices

**Question:** Which cities have the highest average property prices?

In [ ]:
query9 = """
SELECT
    City,
    ROUND(AVG(Price), 2) AS Average_Price
FROM Listings
GROUP BY City
ORDER BY Average_Price DESC;
"""

pd.read_sql_query(query9, conn)

          City  Average_Price
0     New York     2493319.74
1      Phoenix     2459961.76
2  Los Angeles     2442418.31
3      Houston     2436811.00
4      Chicago     2430677.90

## Query 10: Property Distribution by Price Buckets

**Question:** How are properties distributed across price buckets?

In [ ]:
query10 = """
SELECT
    CASE
        WHEN Price < 5000000 THEN 'Below 50 Lakhs'
        WHEN Price BETWEEN 5000000 AND 10000000 THEN '50 Lakhs - 1 Crore'
        ELSE 'Above 1 Crore'
    END AS Price_Bucket,
    COUNT(*) AS Total_Properties
FROM Listings
GROUP BY Price_Bucket
ORDER BY Total_Properties DESC;
"""

pd.read_sql_query(query10, conn)

     Price_Bucket  Total_Properties
0  Below 50 Lakhs             21200

## Query 11: Average Days on Market by City

**Question:** What is the average number of days properties remain on the market in each city?

In [ ]:
query11 = """
SELECT
    l.City,
    ROUND(AVG(s.Days_on_Market), 2) AS Average_Days_On_Market
FROM Listings l
INNER JOIN Sales s
ON l.Listing_ID = s.Listing_ID
GROUP BY l.City
ORDER BY Average_Days_On_Market DESC;
"""

pd.read_sql_query(query11, conn)

          City  Average_Days_On_Market
0  Los Angeles                   65.13
1      Chicago                   64.25
2     New York                   60.85
3      Phoenix                   59.65
4      Houston                   58.51

## Query 12: Fastest Selling Property Types

**Question:** Which property types sell the fastest?

In [ ]:
query12 = """
SELECT
    l.Property_Type,
    ROUND(AVG(s.Days_on_Market), 2) AS Average_Days_On_Market
FROM Listings l
INNER JOIN Sales s
ON l.Listing_ID = s.Listing_ID
GROUP BY l.Property_Type
ORDER BY Average_Days_On_Market ASC;
"""

pd.read_sql_query(query12, conn)

  Property_Type  Average_Days_On_Market
0         House                   58.34
1     Apartment                   60.65
2     Townhouse                   60.96
3         Condo                   66.54

## Query 13: Percentage of Properties Sold Above Listing Price

**Question:** What percentage of properties were sold above the listing price?

In [ ]:
query13 = """
SELECT
    ROUND(
        (SUM(CASE WHEN s.Sale_Price > l.Price THEN 1 ELSE 0 END) * 100.0)
        / COUNT(*), 2
    ) AS Percentage_Sold_Above_Listing
FROM Listings l
INNER JOIN Sales s
ON l.Listing_ID = s.Listing_ID;
"""

pd.read_sql_query(query13, conn)

   Percentage_Sold_Above_Listing
0                          49.31

## Query 14: Sale-to-List Price Ratio by City

**Question:** What is the sale-to-list price ratio by city?

In [ ]:
query14 = """
SELECT
    l.City,
    ROUND(AVG((s.Sale_Price / l.Price) * 100), 2) AS Sale_To_List_Ratio
FROM Listings l
INNER JOIN Sales s
ON l.Listing_ID = s.Listing_ID
GROUP BY l.City
ORDER BY Sale_To_List_Ratio DESC;
"""

pd.read_sql_query(query14, conn)

          City  Sale_To_List_Ratio
0      Chicago              100.15
1      Houston              100.00
2  Los Angeles               99.98
3     New York               99.96
4      Phoenix               99.89

## Query 15: Listings That Took More Than 90 Days to Sell

**Question:** Which listings took more than 90 days to sell?

In [ ]:
query15 = """
SELECT
    l.Listing_ID,
    l.City,
    l.Property_Type,
    s.Days_on_Market
FROM Listings l
INNER JOIN Sales s
ON l.Listing_ID = s.Listing_ID
WHERE s.Days_on_Market > 90
ORDER BY s.Days_on_Market DESC;
"""

pd.read_sql_query(query15, conn)

    Listing_ID         City Property_Type  Days_on_Market
0       L00157      Phoenix     Townhouse      120.018183
1       L00179      Chicago         Condo      120.011468
2       L00259      Phoenix     Apartment      120.010958
3       L00067      Chicago     Apartment      119.993220
4       L00287      Houston     Townhouse      119.970137
5       L00078  Los Angeles         House      119.008925
6       L01134      Chicago         Condo      119.006503
7       L00351      Phoenix         Condo      119.004860
8       L00057      Phoenix         Condo      119.000362
9       L00690      Phoenix     Townhouse      118.997563
10      L00910  Los Angeles         Condo      118.997226
11      L00348     New York         Condo      118.989722
12      L00974     New York     Townhouse      118.989021
13      L00271     New York         House      118.988624
14      L00862      Houston         Condo      118.981480
15      L00455      Chicago     Townhouse      118.981246
16      L01195  Los Angeles     Townhouse      118.010280
17      L00723      Chicago         Condo      118.008767
18      L00457  Los Angeles     Townhouse      118.003937
19      L00405      Chicago         House      117.997501
20      L00410      Chicago         Condo      117.994543
21      L00810      Phoenix         Condo      117.974433
22      L00326  Los Angeles     Apartment      116.984120
23      L01015      Houston         Condo      116.978478
24      L00484      Chicago     Townhouse      116.006934
25      L00849     New York     Townhouse      116.004108
26      L00782     New York         House      116.002914
27      L00555  Los Angeles         Condo      116.001930
28      L00059      Chicago     Townhouse      116.000152
29      L00833      Phoenix         Condo      115.988897
30      L00004      Phoenix     Apartment      115.987802
31      L00417      Houston         Condo      115.987366
32      L00542      Phoenix         House      115.000514
33      L00367      Chicago         House      114.993726
34      L00532      Chicago     Townhouse      114.993099
35      L00215      Phoenix     Apartment      114.009945
36      L01073  Los Angeles     Apartment      114.006340
37      L00905      Chicago     Apartment      114.005013
38      L00145      Chicago         House      114.002268
39      L00110      Chicago         Condo      114.001798
40      L00266  Los Angeles         Condo      114.000828
41      L01032      Chicago     Apartment      113.990738
42      L00835      Phoenix     Townhouse      113.014009
43      L00381      Phoenix     Apartment      113.007285
44      L00758      Phoenix         Condo      112.997793
45      L00558      Phoenix         Condo      112.994292
46      L00683     New York         Condo      112.006042
47      L00213  Los Angeles         House      112.005205
48      L00629  Los Angeles     Townhouse      112.003985
49      L00333      Phoenix         House      111.023103
50      L00312  Los Angeles     Townhouse      111.004496
51      L00943      Phoenix         Condo      110.999033
52      L01006      Houston         Condo      110.996097
53      L00411     New York         House      110.995035
54      L00301      Houston         House      110.005879
55      L00817      Phoenix     Townhouse      110.001527
56      L00340      Phoenix     Apartment      109.990669
57      L01151      Chicago     Townhouse      109.011825
58      L00696      Phoenix     Apartment      109.009282
59      L00631     New York     Apartment      108.995586
60      L00997  Los Angeles     Apartment      108.984132
61      L00252      Chicago         Condo      108.012367
62      L00007  Los Angeles         House      108.007754
63      L00618      Chicago         Condo      108.001717
64      L00236     New York     Townhouse      108.001634
65      L00031     New York         Condo      107.993857
66      L00352     New York         Condo      107.990535
67      L00831      Houston         House      107.979480
68      L00070     New York     Apartment      107.015563
69      L00599  Los Angeles     Townhouse      107.002661
70      L00671      Chicago         House      107.001103
71      L00967  Los Angeles         House      107.001034
72      L01120  Los Angeles     Apartment      107.000871
73      L00412      Houston         House      106.990553
74      L00716      Houston         Condo      106.015983
75      L00358      Chicago     Apartment      106.012449
76      L00933      Phoenix         Condo      106.011495
77      L00225      Chicago     Apartment      106.008208
78      L00212      Chicago         Condo      106.008134
79      L01166  Los Angeles     Apartment      106.006067
80      L00454     New York         Condo      106.004507
81      L00330      Houston     Townhouse      105.997642
82      L00945      Houston         Condo      105.995633
83      L00273  Los Angeles     Apartment      105.992468
84      L00669      Houston     Townhouse      105.013619
85      L00279      Chicago         Condo      105.006325
86      L00760  Los Angeles         House      104.997458
87      L00591      Houston         Condo      104.996145
88      L00694      Chicago     Townhouse      104.983546
89      L01067     New York         House      104.015179
90      L00507     New York         Condo      104.008286
91      L00562  Los Angeles         Condo      104.004988
92      L00193     New York     Apartment      103.997187
93      L01004  Los Angeles     Townhouse      103.994491
94      L00090      Chicago         Condo      103.994363
95      L00083      Phoenix     Apartment      103.988554
96      L00276     New York         House      103.983358
97      L00335      Phoenix     Townhouse      103.011917
98      L00356     New York     Apartment      103.011706
99      L00428      Phoenix         House      103.011351
100     L01038      Houston         Condo      103.002993
101     L00209     New York         Condo      103.001461
102     L00937  Los Angeles         Condo      102.998680
103     L00042  Los Angeles     Apartment      102.997288
104     L00968      Phoenix     Townhouse      102.996685
105     L00622  Los Angeles         Condo      102.995573
106     L00931      Houston     Apartment      102.989311
107     L00768      Houston         House      102.988677
108     L00281      Chicago         Condo      102.984458
109     L00483  Los Angeles         House      102.017787
110     L00462      Phoenix         House      102.012475
111     L01137     New York     Apartment      102.010227
112     L00536     New York     Apartment      102.005995
113     L00166  Los Angeles     Townhouse      101.999686
114     L00691  Los Angeles         Condo      101.992142
115     L01159      Phoenix     Apartment      101.983472
116     L00177      Chicago     Apartment      101.015963
117     L00496     New York         Condo      101.010488
118     L00319     New York         Condo      101.005703
119     L00808     New York     Townhouse      100.997689
120     L00043      Houston     Townhouse      100.985113
121     L00427      Phoenix         Condo      100.011920
122     L00133      Houston     Townhouse      100.003195
123     L00366  Los Angeles     Townhouse       99.994277
124     L00322      Chicago         House       99.989387
125     L00139  Los Angeles     Townhouse       99.010263
126     L00737      Houston     Townhouse       99.006599
127     L00134  Los Angeles     Townhouse       99.005723
128     L01090      Houston         House       99.004024
129     L00655      Chicago         House       99.003717
130     L01091      Phoenix     Apartment       98.996927
131     L00556      Chicago         House       98.996264
132     L01178      Houston     Apartment       98.991041
133     L00721     New York     Apartment       98.974608
134     L00165  Los Angeles     Apartment       98.006200
135     L00430      Chicago     Apartment       98.002756
136     L00708      Phoenix         Condo       97.997782
137     L01117      Phoenix         House       97.997300
138     L01066  Los Angeles         Condo       97.996652
139     L00126      Chicago     Apartment       97.982857
140     L00717     New York         Condo       97.008084
141     L00449     New York     Townhouse       97.007171
142     L00224     New York         Condo       97.005575
143     L00052     New York     Apartment       96.997823
144     L00765  Los Angeles         House       96.992046
145     L00486     New York     Apartment       96.003472
146     L00315     New York     Apartment       95.990879
147     L00605     New York         Condo       95.013133
148     L00680      Houston     Apartment       95.009388
149     L00114      Phoenix     Apartment       95.008960
150     L00715     New York         House       95.005313
151     L00569      Phoenix         Condo       95.005210
152     L00827      Phoenix         House       95.004838
153     L00115      Houston         House       94.999253
154     L00588      Phoenix         House       94.996521
155     L00056  Los Angeles     Apartment       94.009523
156     L00577  Los Angeles     Townhouse       94.000995
157     L00949  Los Angeles     Townhouse       93.999888
158     L00132     New York         Condo       93.998240
159     L00846      Chicago     Apartment       93.997274
160     L01012     New York     Apartment       93.997174
161     L00124     New York     Apartment       93.990422
162     L00200     New York     Townhouse       93.989146
163     L00450     New York         House       93.022375
164     L00964      Chicago         House       93.005286
165     L00543     New York         Condo       93.003745
166     L00619     New York     Apartment       92.999795
167     L00265      Houston     Townhouse       92.997851
168     L00907      Chicago     Townhouse       92.996210
169     L00240  Los Angeles     Apartment       92.995723
170     L00890     New York     Townhouse       92.994440
171     L00044     New York     Apartment       92.993585
172     L01115     New York     Townhouse       92.989417
173     L00241      Phoenix         Condo       92.020419
174     L00802      Chicago         Condo       92.015788
175     L00789      Houston         House       92.006279
176     L00842  Los Angeles         Condo       92.003260
177     L00028     New York         Condo       91.990841
178     L00211      Chicago         Condo       91.989885
179     L00865      Chicago         House       91.024915
180     L00880  Los Angeles     Apartment       91.017787
181     L00024  Los Angeles     Townhouse       91.017666
182     L00108      Phoenix     Townhouse       91.006515
183     L00164      Houston         Condo       91.005406
184     L00071      Chicago         House       91.003344
185     L00452  Los Angeles         House       90.996134
186     L00045  Los Angeles         House       90.992445
187     L00812      Houston         House       90.990111
188     L00568      Chicago         House       90.006266
189     L00992      Houston         House       90.003498

## Query 16: Metro Distance vs Time on Market

**Question:** How does metro distance affect time on market?

In [ ]:
query16 = """
SELECT
    CASE
        WHEN p.metro_distance_km <= 2 THEN 'Near Metro'
        WHEN p.metro_distance_km <= 5 THEN 'Moderate Distance'
        ELSE 'Far from Metro'
    END AS Metro_Category,
    ROUND(AVG(s.Days_on_Market), 2) AS Average_Days_On_Market
FROM Listings l
INNER JOIN Properties p
ON l.Listing_ID = p.listing_id
INNER JOIN Sales s
ON l.Listing_ID = s.Listing_ID
GROUP BY Metro_Category
ORDER BY Average_Days_On_Market;
"""

pd.read_sql_query(query16, conn)

      Metro_Category  Average_Days_On_Market
0     Far from Metro                   60.67
1  Moderate Distance                   60.94
2         Near Metro                   64.75

## Query 17: Monthly Sales Trend

**Question:** What is the monthly sales trend?

In [ ]:
query17 = """
SELECT
    strftime('%Y-%m', Date_Sold) AS Sale_Month,
    COUNT(*) AS Total_Sales
FROM Sales
GROUP BY Sale_Month
ORDER BY Sale_Month;
"""

pd.read_sql_query(query17, conn)

   Sale_Month  Total_Sales
0     2023-01            7
1     2023-02           17
2     2023-03           20
3     2023-04           36
4     2023-05           45
5     2023-06           31
6     2023-07           48
7     2023-08           50
8     2023-09           46
9     2023-10           64
10    2023-11           46
11    2023-12           42
12    2024-01           44
13    2024-02           44
14    2024-03           39
15    2024-04           29
16    2024-05           45
17    2024-06           29
18    2024-07           24
19    2024-08           13
20    2024-09            1

## Query 18: Properties Currently Unsold

**Question:** Which properties are currently unsold?

In [ ]:
query18 = """
SELECT
    l.Listing_ID,
    l.City,
    l.Property_Type,
    l.Price
FROM Listings l
LEFT JOIN Sales s
ON l.Listing_ID = s.Listing_ID
WHERE s.Listing_ID IS NULL
LIMIT 20;
"""

pd.read_sql_query(query18, conn)

   Listing_ID         City Property_Type         Price
0      L00002  Los Angeles     Apartment  1.519141e+06
1      L00005      Phoenix     Townhouse  5.622970e+05
2      L00009     New York     Townhouse  1.224551e+06
3      L00014      Chicago     Apartment  1.377440e+06
4      L00015  Los Angeles         House  1.069429e+06
5      L00016      Phoenix         House  1.535740e+06
6      L00017     New York         House  1.823444e+06
7      L00018      Houston         Condo  2.388070e+05
8      L00020      Houston         House  6.554930e+05
9      L00021      Phoenix         Condo  1.666601e+06
10     L00022      Houston         Condo  5.599480e+05
11     L00023     New York     Apartment  1.905863e+06
12     L00027      Chicago     Apartment  7.155140e+05
13     L00033      Phoenix         House  3.692560e+05
14     L00035      Phoenix         House  1.595162e+06
15     L00036      Chicago     Townhouse  1.986627e+06
16     L00037  Los Angeles         House  2.342720e+05
17     L00038      Phoenix         House  1.334048e+06
18     L00039     New York         House  2.413480e+05
19     L00041  Los Angeles     Townhouse  6.096020e+05

## Query 19: Which agents have closed the most sales?

**Question:** Which agents have closed the most sales?

In [ ]:
query19 = """
SELECT
    a.Name,
    COUNT(s.Listing_ID) AS Total_Sales
FROM Agents a
INNER JOIN Listings l
ON a.Agent_ID = l.Agent_ID
INNER JOIN Sales s
ON l.Listing_ID = s.Listing_ID
GROUP BY a.Agent_ID, a.Name
ORDER BY Total_Sales DESC;
"""

pd.read_sql_query(query19, conn)

           Name  Total_Sales
0   Agent A0042           25
1   Agent A0011           24
2   Agent A0014           21
3   Agent A0035           21
4   Agent A0043           20
5   Agent A0046           20
6   Agent A0007           19
7   Agent A0048           19
8   Agent A0027           18
9   Agent A0029           18
10  Agent A0009           17
11  Agent A0019           17
12  Agent A0021           17
13  Agent A0025           17
14  Agent A0050           17
15  Agent A0003           16
16  Agent A0015           16
17  Agent A0033           16
18  Agent A0036           16
19  Agent A0039           16
20  Agent A0001           15
21  Agent A0006           15
22  Agent A0010           15
23  Agent A0016           15
24  Agent A0041           15
25  Agent A0017           14
26  Agent A0024           14
27  Agent A0047           14
28  Agent A0018           13
29  Agent A0031           13
30  Agent A0040           13
31  Agent A0045           13
32  Agent A0023           12
33  Agent A0026           12
34  Agent A0037           12
35  Agent A0038           12
36  Agent A0004           11
37  Agent A0008           11
38  Agent A0012           11
39  Agent A0030           11
40  Agent A0005           10
41  Agent A0020           10
42  Agent A0028           10
43  Agent A0032           10
44  Agent A0049           10
45  Agent A0022            9
46  Agent A0002            8
47  Agent A0044            8
48  Agent A0013            7
49  Agent A0034            7

## Query 20: Who are the top agents by total sales revenue?

**Question:** Who are the top agents by total sales revenue?

In [ ]:
query20 = """
SELECT
    a.Name,
    ROUND(SUM(s.Sale_Price),2) AS Total_Sales_Revenue
FROM Agents a
INNER JOIN Listings l
ON a.Agent_ID = l.Agent_ID
INNER JOIN Sales s
ON l.Listing_ID = s.Listing_ID
GROUP BY a.Agent_ID, a.Name
ORDER BY Total_Sales_Revenue DESC;
"""

pd.read_sql_query(query20, conn)

           Name  Total_Sales_Revenue
0   Agent A0011          27882272.02
1   Agent A0042          27191605.99
2   Agent A0043          24102418.02
3   Agent A0035          22725751.99
4   Agent A0014          22034008.02
5   Agent A0046          21335804.97
6   Agent A0048          21186306.00
7   Agent A0027          21099696.96
8   Agent A0009          20279274.97
9   Agent A0029          19586498.02
10  Agent A0039          19223013.98
11  Agent A0036          19209543.94
12  Agent A0050          18968547.96
13  Agent A0025          18818591.05
14  Agent A0017          18583851.04
15  Agent A0007          18414480.00
16  Agent A0001          18173919.98
17  Agent A0015          17752856.04
18  Agent A0019          16730611.98
19  Agent A0021          16548308.01
20  Agent A0006          16523231.01
21  Agent A0031          15723293.00
22  Agent A0003          15584954.00
23  Agent A0018          15539876.00
24  Agent A0012          14730534.97
25  Agent A0023          14634873.95
26  Agent A0010          14228164.00
27  Agent A0033          14202148.96
28  Agent A0041          14077482.03
29  Agent A0049          13954945.00
30  Agent A0047          13478182.00
31  Agent A0016          13450352.05
32  Agent A0024          13196018.04
33  Agent A0004          12754766.05
34  Agent A0030          12484445.00
35  Agent A0037          12314990.00
36  Agent A0040          12039288.01
37  Agent A0045          11819072.04
38  Agent A0002          11754965.99
39  Agent A0008          11071897.04
40  Agent A0038          11060638.02
41  Agent A0032          10653319.95
42  Agent A0044          10247548.02
43  Agent A0005          10114386.01
44  Agent A0028           9831891.01
45  Agent A0020           9605503.02
46  Agent A0013           9114420.00
47  Agent A0026           8479517.99
48  Agent A0034           7011394.01
49  Agent A0022           6303600.99

## Query 21: Which agents close deals fastest?

**Question:** Which agents close deals fastest?

In [ ]:
query21 = """
SELECT
    Name,
    avg_closing_days
FROM Agents
ORDER BY avg_closing_days ASC;
"""

pd.read_sql_query(query21, conn)

           Name  avg_closing_days
0   Agent A0048                15
1   Agent A0035                20
2   Agent A0042                21
3   Agent A0023                23
4   Agent A0045                26
5   Agent A0041                27
6   Agent A0016                31
7   Agent A0034                31
8   Agent A0028                33
9   Agent A0032                33
10  Agent A0047                33
11  Agent A0049                33
12  Agent A0044                35
13  Agent A0027                36
14  Agent A0009                38
15  Agent A0018                39
16  Agent A0026                42
17  Agent A0022                44
18  Agent A0025                48
19  Agent A0006                49
20  Agent A0040                52
21  Agent A0029                56
22  Agent A0033                57
23  Agent A0017                58
24  Agent A0046                58
25  Agent A0011                60
26  Agent A0031                60
27  Agent A0004                61
28  Agent A0019                62
29  Agent A0001                64
30  Agent A0013                65
31  Agent A0020                65
32  Agent A0005                67
33  Agent A0007                68
34  Agent A0050                68
35  Agent A0036                69
36  Agent A0008                72
37  Agent A0039                76
38  Agent A0021                77
39  Agent A0030                77
40  Agent A0037                77
41  Agent A0024                79
42  Agent A0002                82
43  Agent A0012                82
44  Agent A0003                83
45  Agent A0015                84
46  Agent A0038                84
47  Agent A0014                85
48  Agent A0043                89
49  Agent A0010                90

## Query 22: Does experience correlate with deals closed?

**Question:** Does experience correlate with deals closed?

In [ ]:
query22 = """
SELECT
    experience_years,
    AVG(deals_closed) AS Average_Deals_Closed
FROM Agents
GROUP BY experience_years
ORDER BY experience_years;
"""

pd.read_sql_query(query22, conn)

    experience_years  Average_Deals_Closed
0                  1            262.000000
1                  2             50.000000
2                  3             14.000000
3                  4            140.000000
4                  5             88.333333
5                  7             73.000000
6                  9            283.000000
7                 10             93.500000
8                 11            109.000000
9                 12            257.000000
10                13            194.333333
11                14             72.000000
12                15            123.000000
13                16             94.500000
14                17            258.500000
15                18            107.333333
16                19            112.500000
17                20            138.000000
18                21            217.800000
19                22             98.000000
20                23            165.000000
21                25             73.500000

## Query 23: Do agents with higher ratings close deals faster?

**Question:** Do agents with higher ratings close deals faster?

In [ ]:
query23 = """
SELECT
    rating,
    ROUND(AVG(avg_closing_days),2) AS Average_Closing_Days
FROM Agents
GROUP BY rating
ORDER BY rating DESC;
"""

pd.read_sql_query(query23, conn)

    rating  Average_Closing_Days
0      5.0                 53.50
1      4.9                 54.50
2      4.8                 51.00
3      4.6                 36.00
4      4.5                 61.00
5      4.4                 38.00
6      4.3                 58.80
7      4.2                 26.00
8      4.1                 55.83
9      4.0                 27.00
10     3.8                 75.00
11     3.7                 77.00
12     3.6                 56.40
13     3.5                 75.33
14     3.4                 60.67
15     3.3                 55.00
16     3.2                 59.75
17     3.1                 50.00

## Query 24: What is the average commission earned by each agent?

**Question:** What is the average commission earned by each agent?

In [ ]:
query24 = """
SELECT
    a.Name,
    ROUND(AVG(s.Sale_Price * a.commission_rate / 100), 2) AS Average_Commission
FROM Agents a
INNER JOIN Listings l
ON a.Agent_ID = l.Agent_ID
INNER JOIN Sales s
ON l.Listing_ID = s.Listing_ID
GROUP BY a.Agent_ID, a.Name
ORDER BY Average_Commission DESC;
"""

pd.read_sql_query(query24, conn)

           Name  Average_Commission
0   Agent A0009            33997.61
1   Agent A0002            32326.16
2   Agent A0035            32032.49
3   Agent A0012            31737.61
4   Agent A0030            31665.09
5   Agent A0018            31438.36
6   Agent A0031            30358.05
7   Agent A0050            28564.40
8   Agent A0017            28406.74
9   Agent A0024            27805.90
10  Agent A0003            27760.70
11  Agent A0019            27556.30
12  Agent A0032            27379.03
13  Agent A0029            26659.40
14  Agent A0021            26574.64
15  Agent A0020            25646.69
16  Agent A0034            24640.04
17  Agent A0042            24363.68
18  Agent A0001            24231.89
19  Agent A0049            23723.41
20  Agent A0011            23351.40
21  Agent A0013            23176.67
22  Agent A0023            23049.93
23  Agent A0045            22728.98
24  Agent A0033            22723.44
25  Agent A0027            22506.34
26  Agent A0025            22250.22
27  Agent A0028            22121.75
28  Agent A0043            21089.62
29  Agent A0036            20770.32
30  Agent A0014            20670.00
31  Agent A0010            20298.85
32  Agent A0004            19364.05
33  Agent A0044            18573.68
34  Agent A0037            18267.24
35  Agent A0006            17404.47
36  Agent A0008            17312.42
37  Agent A0007            17251.46
38  Agent A0046            16748.61
39  Agent A0015            16532.35
40  Agent A0039            16459.71
41  Agent A0047            15692.45
42  Agent A0048            14941.92
43  Agent A0040            14632.37
44  Agent A0022            13587.76
45  Agent A0016            13002.01
46  Agent A0041            12388.18
47  Agent A0026            11518.01
48  Agent A0038            11244.98
49  Agent A0005            11226.97

## Query 25: Which agents currently have the most active listings?

**Question:** Which agents currently have the most active listings?

In [ ]:
query25 = """
SELECT
    a.Name,
    COUNT(l.Listing_ID) AS Active_Listings
FROM Agents a
INNER JOIN Listings l
ON a.Agent_ID = l.Agent_ID
LEFT JOIN Sales s
ON l.Listing_ID = s.Listing_ID
WHERE s.Listing_ID IS NULL
GROUP BY a.Agent_ID, a.Name
ORDER BY Active_Listings DESC;
"""

pd.read_sql_query(query25, conn)

           Name  Active_Listings
0   Agent A0023              446
1   Agent A0011              439
2   Agent A0008              438
3   Agent A0042              435
4   Agent A0014              432
5   Agent A0044              430
6   Agent A0020              426
7   Agent A0012              425
8   Agent A0015              425
9   Agent A0048              425
10  Agent A0016              424
11  Agent A0018              422
12  Agent A0031              422
13  Agent A0036              422
14  Agent A0033              418
15  Agent A0022              417
16  Agent A0040              416
17  Agent A0010              415
18  Agent A0027              415
19  Agent A0002              414
20  Agent A0037              413
21  Agent A0005              412
22  Agent A0026              412
23  Agent A0007              411
24  Agent A0035              410
25  Agent A0045              410
26  Agent A0009              409
27  Agent A0021              409
28  Agent A0050              409
29  Agent A0043              408
30  Agent A0028              407
31  Agent A0004              406
32  Agent A0032              404
33  Agent A0047              404
34  Agent A0006              403
35  Agent A0038              401
36  Agent A0041              399
37  Agent A0046              397
38  Agent A0030              396
39  Agent A0013              395
40  Agent A0029              395
41  Agent A0001              392
42  Agent A0017              388
43  Agent A0034              388
44  Agent A0049              387
45  Agent A0019              386
46  Agent A0025              384
47  Agent A0024              380
48  Agent A0039              380
49  Agent A0003              379

## Query 26: What percentage of buyers are investors vs end users?

**Question:** What percentage of buyers are investors vs end users?

In [ ]:
query26 = """
SELECT
    buyer_type,
    COUNT(*) AS Total_Buyers,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM Buyers), 2) AS Percentage
FROM Buyers
GROUP BY buyer_type
ORDER BY Percentage DESC;
"""

pd.read_sql_query(query26, conn)

  buyer_type  Total_Buyers  Percentage
0   End User         10020        50.1
1   Investor          9980        49.9

## Query 27: Which cities have the highest loan uptake rate?

**Question:** Which cities have the highest loan uptake rate?

In [ ]:
query27 = """
SELECT
    l.City,
    ROUND(AVG(b.loan_taken) * 100, 2) AS Loan_Uptake_Rate
FROM Buyers b
INNER JOIN Listings l
ON b.sale_id = l.Listing_ID
GROUP BY l.City
ORDER BY Loan_Uptake_Rate DESC;
"""

pd.read_sql_query(query27, conn)

          City  Loan_Uptake_Rate
0  Los Angeles             50.99
1      Chicago             50.57
2     New York             50.22
3      Houston             49.71
4      Phoenix             49.50

## Query 28: What is the average loan amount by buyer type?

**Question:** What is the average loan amount by buyer type?

In [ ]:
query28 = """
SELECT
    buyer_type,
    ROUND(AVG(loan_amount), 2) AS Average_Loan_Amount
FROM Buyers
WHERE loan_taken = 1
GROUP BY buyer_type
ORDER BY Average_Loan_Amount DESC;
"""

pd.read_sql_query(query28, conn)

  buyer_type  Average_Loan_Amount
0   Investor           5211545.97
1   End User           5210307.45

## Query 29: Which payment mode is most commonly used?

**Question:** Which payment mode is most commonly used?

In [ ]:
query29 = """
SELECT
    payment_mode,
    COUNT(*) AS Total_Transactions
FROM Buyers
GROUP BY payment_mode
ORDER BY Total_Transactions DESC;
"""

pd.read_sql_query(query29, conn)

    payment_mode  Total_Transactions
0           Cash                5088
1            UPI                5012
2         Cheque                4951
3  Bank Transfer                4949

## Query 30: Do loan-backed purchases take longer to close?

**Question:** Do loan-backed purchases take longer to close?

In [ ]:
query30 = """
SELECT
    CASE
        WHEN b.loan_taken = 1 THEN 'Loan Taken'
        ELSE 'No Loan'
    END AS Loan_Status,
    ROUND(AVG(s.Days_on_Market), 2) AS Average_Days_On_Market
FROM Buyers b
INNER JOIN Sales s
ON b.sale_id = s.Listing_ID
GROUP BY Loan_Status;
"""

pd.read_sql_query(query30, conn)

  Loan_Status  Average_Days_On_Market
0  Loan Taken                   62.15
1     No Loan                   61.07

In [ ]:

import pandas as pd
import sqlite3

conn = sqlite3.connect("brickview.db")

print(pd.read_sql_query("SELECT * FROM Listings LIMIT 5", conn))

conn.close()

  Listing_ID         City Property_Type         Price         Sqft  \
0     L00001     New York     Apartment  1.655144e+06  2753.009121
1     L00002  Los Angeles     Apartment  1.519141e+06  4966.988193
2     L00003      Houston     Apartment  1.624890e+05  1267.003959
3     L00004      Phoenix     Apartment  1.277016e+06  2128.014429
4     L00005      Phoenix     Townhouse  5.622970e+05  4178.997421

  Date_Listed Agent_ID   Latitude   Longitude
0  2023-05-06    A0015  33.965208  -69.861589
1  2023-02-14    A0038  42.547892  -90.277860
2  2023-04-22    A0015  28.732327 -115.952982
3  2024-01-02    A0042  26.403938  -74.771490
4  2023-10-29    A0018  39.425252  -83.917878